### ISSUE TITLE
Make codestyle consistent with other BEM projects

### ISSUE THREAD

**Issue by tadatuta** [bem-contrib/markdown-bemjson#4]

**Comment by 4ok** [comment]
Where I can see BEM projects codestyle?

**Comment by tadatuta** [comment]
Current state is [here](https://github.com/blond/jscs-bem), but I'd better to ask @blond if it's ready for integration.

**Comment by blond** [comment]
No, not ready.

**Comment by blond** [comment]
I recommend to use [eslint-config-pedant](https://github.com/blond/eslint-config-pedant) for all bem projects. 

This package intentionally does not limit your choice of code style, but helps with find errors, typos and potentially dangerous code.

Now it is used in [bem-naming](https://github.com/bem/bem-naming) and [bem.info](https://github.com/vithar/bem.info).

**Comment by 4ok** [comment]
thanks
