### ISSUE TITLE
Rewrite engine to use "markdown-it" markdown parser

### ISSUE THREAD

**Issue by 4ok** [bem-contrib/markdown-bemjson#8]
Now used not supported "marked" (https://github.com/chjj/marked.git). 
Want to use "markdown-it" (https://github.com/markdown-it/markdown-it)

**Comment by Realetive** [comment]
`marked` look like more alive: https://github.com/chjj/marked/pulse/monthly vs. https://github.com/markdown-it/markdown-it/pulse/monthly

**Comment by 4ok** [comment]
@Realetive You are right

**Comment by tadatuta** [comment]
see also: https://github.com/bem-contrib/md-to-bemjson
